define([], function() {
  return {
    "Title": "Global Header",
    "NavigationLabel": "Global navigation",
    "OverviewLabel": "Overview",
    "CurrentPageLabel": "Current page",
    "CurrentSectionLabel": "Current section",
    "SectionCountSingleLabel": "{0} section",
    "SectionCountLabel": "{0} sections",
    "ChromeFallbackLabel": "English labels",
    "OpenMenuLabel": "Open navigation menu",
    "CloseMenuLabel": "Close navigation menu",
    "LoadingLabel": "Loading navigation",
    "HomeAriaLabel": "Go to the home page",
    "BackButtonLabel": "Back",
    "ViewAllLabel": "View all",
    "ViewAllForLabel": "View all {0}",
    "FeaturedLabel": "Featured",
    "SkipToNavigationLabel": "Skip to navigation",
    "SubmenuAriaLabel": "Open {0} submenu",
    "MobileBreadcrumbsAriaLabel": "Mobile navigation breadcrumbs",
    "SkipNavigationTargetAriaLabel": "Navigation",
    "NavigationUnavailableLabel": "Navigation unavailable",
    "EmptySectionLabel": "No items in this section",
    "SearchPlaceholder": "Search",
    "SearchAriaLabel": "Search the intranet",
    "SearchSuggestionsLabel": "Search suggestions",
    "RecentSearchesLabel": "Recent searches",
    "UserMenuAriaLabel": "User menu",
    "NotificationsAriaLabel": "Notifications",
    "NotificationsEmptyLabel": "No new notifications",
    "AppLauncherAriaLabel": "App launcher",
    "QuickActionsAriaLabel": "Quick actions",
    "LanguageSwitcherAriaLabel": "Change language",
    "ThemeLightLabel": "Light",
    "ThemeDarkLabel": "Dark",
    "BookmarksAriaLabel": "Bookmarks",
    "AdminSettingsAriaLabel": "Administration",
    "HelpAriaLabel": "Help",
    "SiteSwitcherAriaLabel": "Switch site",
    "FeedbackAriaLabel": "Feedback",
    "PrintAriaLabel": "Print this page",
    "ShareAriaLabel": "Share this page",
    "BackToTopAriaLabel": "Back to top",
    "AccessibilityToolsAriaLabel": "Accessibility tools",
    "HighContrastLabel": "High contrast",
    "TextSizeLabel": "Text size",
    "BreadcrumbsAriaLabel": "Breadcrumbs",
    "BookmarksEmptyLabel": "No bookmarks yet",
    "MyProfileLabel": "My profile",
    "SignOutLabel": "Sign out"
  };
});