define([], function() {
  return {
    "Title": "Epiroc Header",
    "NavigationLabel": "Global navigering",
    "OverviewLabel": "Översikt",
    "CurrentPageLabel": "Aktuell sida",
    "CurrentSectionLabel": "Aktuellt avsnitt",
    "SectionCountSingleLabel": "{0} avsnitt",
    "SectionCountLabel": "{0} avsnitt",
    "ChromeFallbackLabel": "Engelska etiketter",
    "OpenMenuLabel": "Öppna navigeringsmenyn",
    "CloseMenuLabel": "Stäng navigeringsmenyn",
    "LoadingLabel": "Laddar navigering",
    "HomeAriaLabel": "Gå till Epirocs startsida",
    "BackButtonLabel": "Tillbaka",
    "ViewAllLabel": "Visa alla",
    "ViewAllForLabel": "Visa alla {0}",
    "FeaturedLabel": "Utvalda",
    "SkipToNavigationLabel": "Hoppa till navigering",
    "SubmenuAriaLabel": "Öppna {0} undermeny",
    "MobileBreadcrumbsAriaLabel": "Mobil navigering brödsmulor",
    "SkipNavigationTargetAriaLabel": "Navigering",
    "NavigationUnavailableLabel": "Navigering otillgänglig",
    "EmptySectionLabel": "Inga objekt i detta avsnitt",
    "SearchPlaceholder": "Sök",
    "SearchAriaLabel": "Sök på intranätet",
    "SearchSuggestionsLabel": "Sökförslag",
    "RecentSearchesLabel": "Senaste sökningar",
    "UserMenuAriaLabel": "Användarmeny",
    "NotificationsAriaLabel": "Aviseringar",
    "NotificationsEmptyLabel": "Inga nya aviseringar",
    "AppLauncherAriaLabel": "Appöppnare",
    "QuickActionsAriaLabel": "Snabbåtgärder",
    "LanguageSwitcherAriaLabel": "Byt språk",
    "ThemeLightLabel": "Ljust",
    "ThemeDarkLabel": "Mörkt",
    "BookmarksAriaLabel": "Bokmärken",
    "AdminSettingsAriaLabel": "Administration",
    "HelpAriaLabel": "Hjälp",
    "SiteSwitcherAriaLabel": "Byt webbplats",
    "FeedbackAriaLabel": "Feedback",
    "PrintAriaLabel": "Skriv ut denna sida",
    "ShareAriaLabel": "Dela denna sida",
    "BackToTopAriaLabel": "Tillbaka till toppen",
    "AccessibilityToolsAriaLabel": "Hjälpmedelsverktyg",
    "HighContrastLabel": "Hög kontrast",
    "TextSizeLabel": "Textstorlek",
    "BreadcrumbsAriaLabel": "Brödsmulor",
    "BookmarksEmptyLabel": "Inga bokmärken än",
    "MyProfileLabel": "Min profil",
    "SignOutLabel": "Logga ut"
  };
});